export const RECEIVE_JOIN_ROOM = "SEND_JOIN_ROOM";
export const RECEIVE_LEFT_ROOM = "SEND_LEFT_ROOM";
export const RECEIVE_FIRST_QUESTION = "SEND_FIRST_QUESTION";
export const RECEIVE_QUESTION = "SEND_FIRST_QUESTION";
export const RECEIVE_LAST_QUESTION = "SEND_LAST_QUESTION";
export const RECEIVE_STATISTIC = "SEND_STATISTIC";
